export const moodChoices = [
    { name: '😊 Happy', value: 'happy' },
    { name: '😌 Calm', value: 'calm' },
    { name: '😐 Neutral', value: 'neutral' },
    { name: '😔 Sad', value: 'sad' },
    { name: '😟 Anxious', value: 'anxious' },
    { name: '😤 Frustrated', value: 'frustrated' },
    { name: '😴 Tired', value: 'tired' },
    { name: '🤔 Confused', value: 'confused' },
    { name: '😠 Angry', value: 'angry' },
    { name: '😢 Upset', value: 'upset' },
    { name: '😩 Overwhelmed', value: 'overwhelmed' },
    { name: '😶 Numb', value: 'numb' },
    { name: '😬 Stressed', value: 'stressed' },
    { name: '😳 Embarrassed', value: 'embarrassed' },
    { name: '😇 Grateful', value: 'grateful' },
    { name: '😎 Confident', value: 'confident' },
    { name: '🥳 Excited', value: 'excited' },
    { name: '😕 Disappointed', value: 'disappointed' },
    { name: '😱 Afraid', value: 'afraid' },
    { name: '🥺 Lonely', value: 'lonely' },
    { name: '😏 Proud', value: 'proud' },
    { name: '😅 Relieved', value: 'relieved' },
    { name: '🤪 Chaotic', value: 'chaotic' },
    { name: '😈 Frisky', value: 'frisky' },
    { name: '😋 Playful', value: 'playful' }
]

export const moodIntensities = [
    { name: '1 (Very Low)', value: '1' },
    { name: '2 (Low)', value: '2' },
    { name: '3 (Moderate)', value: '3' },
    { name: '4 (High)', value: '4' },
    { name: '5 (Very High)', value: '5' }
]

export const moodEmojis = {
    happy: '😊',
    calm: '😌',
    neutral: '😐',
    sad: '😔',
    anxious: '😟',
    frustrated: '😤',
    tired: '😴',
    confused: '🤔',
    angry: '😠',
    upset: '😢',
    overwhelmed: '😩',
    numb: '😶',
    stressed: '😬',
    embarrassed: '😳',
    grateful: '😇',
    confident: '😎',
    excited: '🥳',
    disappointed: '😕',
    afraid: '😱',
    lonely: '🥺',
    proud: '😏',
    relieved: '😅',
    chaotic: '🤪',
    frisky: '😈',
    playful: '😋',
    bored: '😐',
    overstimulated: '😵‍💫',
    hopeless: '😔',
    blessed: '😇',
    inspired: '🤩',
    determined: '😤',
    content: '😌',
    annoyed: '😒',
    silly: '😜',
    loved: '😚',
    regretful: '😔',
    hopeful: '😇',
    spaced_out: '😶‍🌫️',
    awkward: '😬',
    satisfied: '😌',
    motivated: '😤',
    shocked: '😳',
    peaceful: '😇',
    guilty: '😔',
    drained: '😩',
    exhausted: '😵',
    blank: '😶',
    uncomfortable: '😬',
    zen: '😇'
}
