title: Mellow Documentation
description: Your AI-Powered Mental Health Companion for Discord
baseurl: '/mellow'
url: 'https://thingspace.github.io'

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-sitemap

# Search configuration
search_enabled: true

# Navigation structure
nav_sort: order

# Footer content
footer_content: "Copyright &copy; 2025 Mellow. Mental health support for Discord communities."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External links
aux_links:
  "Mellow on GitHub":
    - "https://github.com/ThingSpace/Mellow"
  "Invite to Discord":
    - "https://discord.com/oauth2/authorize?client_id=1386810331367608371&permissions=1394015504448"
  "Support Server":
    - "https://discord.gg/qyTcK7VRva"

aux_links_new_tab: true

exclude:
    - README.md
    - node_modules/
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/
    - "https://github.com/ThingSpace/Mellow"
  "Invite to Discord":
    - "https://discord.com/oauth2/authorize?client_id=1088267111259533312&permissions=1394015504448&integration_type=0&scope=bot+applications.commands"
  "Support Server":
    - "https://discord.gg/qyTcK7VRva"

aux_links_new_tab: true

exclude:
    - README.md
    - node_modules/
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/
