title: Mellow Documentation
description: Your AI-Powered Mental Health Companion for Discord - Complete documentation, setup guides, and API reference for comprehensive mental health support in Discord servers.
keywords: mental health, AI, Discord, chatbot, support, documentation, Mellow, crisis detection, mood tracking, coping tools
author: ByteBrush Studios
baseurl: ''
url: 'https://mellow.athing.space'

# SEO and social media
lang: en_US
twitter:
    username: MellowBot
    card: summary_large_image

# Site verification (add when available)
# google_site_verification: "your-verification-code"
# bing_site_verification: "your-verification-code"

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-last-modified-at

# Search configuration
search_enabled: true

# Theme settings
theme: just-the-docs
color_scheme: mellow
color_scheme_toggle: true

# Navigation structure (for just-the-docs)
nav_sort: order

# Callouts configuration
callouts_level: quiet
callouts:
    highlight:
        color: yellow
    new:
        title: 'New in v1.1.0'
        color: green
    note:
        title: 'Note'
        color: blue
    warning:
        title: 'Warning'
        color: red

# Table of contents
nav_external_links:
    - title: Mellow on GitHub
      url: https://github.com/ThingSpace/Mellow
    - title: Invite to Discord
      url: https://discord.com/oauth2/authorize?client_id=1386810331367608371
    - title: Support Server
      url: https://discord.gg/C3ZuXPP7Hc

# Footer content
footer_content: 'Copyright &copy; 2025 ByteBrush Studios. All Rights Reserved'

# Back to top link
back_to_top: true
back_to_top_text: 'Back to top'

# External links
aux_links:
    'Mellow on GitHub':
        - 'https://github.com/ThingSpace/Mellow'
    'Invite to Discord':
        - 'https://discord.com/oauth2/authorize?client_id=1386810331367608371'
    'Support Server':
        - 'https://discord.gg/C3ZuXPP7Hc'

aux_links_new_tab: true

exclude:
    - README.md
    - node_modules/
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/
