title: Mellow Documentation
description: Your AI-Powered Mental Health Companion for Discord
keywords: mental health, AI, Discord, chatbot, support, documentation, Mellow
author: ByteBrush Studios
baseurl: ''
url: 'https://mellow.athing.space'

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-sitemap

# Search configuration
search_enabled: true

# Theme settings
theme: just-the-docs
color_scheme: mellow
color_scheme_toggle: true

# Navigation structure (for just-the-docs)
nav_sort: order

# Footer content
footer_content: 'Copyright &copy; 2025 ByteBrush Studios. All Rights Reserved'

# Back to top link
back_to_top: true
back_to_top_text: 'Back to top'

# External links
aux_links:
    'Mellow on GitHub':
        - 'https://github.com/ThingSpace/Mellow'
    'Invite to Discord':
        - 'https://discord.com/oauth2/authorize?client_id=1386810331367608371'
    'Support Server':
        - 'https://discord.gg/C3ZuXPP7Hc'

aux_links_new_tab: true

exclude:
    - README.md
    - node_modules/
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/
