source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

# Additional useful plugins
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"
gem "jekyll-last-modified-at"
